services:
  app:
    image: mparvin/shortener:latest
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    networks:
      - shortener

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - shortener

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - shortener

networks:
  shortener:
    driver: bridge
